name: Fetch Chromium Android Revision
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
         token: ${{ secrets.GH_PERSONAL_TOKEN }}

      - name: Fetch revision
        run: |
          curl -s \
            https://storage.googleapis.com/chromium-browser-snapshots/Android/LAST_CHANGE \
            > LAST_CHANGE

      - name: Commit revision
        run: |

          git config user.name "Naimul Hasan Taky"
          git config user.email "naimulhasantaky@proton.me"

          git add LAST_CHANGE
          git commit -m "Update Chromium Android Revision" || echo "Nothing to commit"
          git push
